// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzkehqpiyzddzvnwxhez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6a2VocXBpeXpkZHp2bnd4aGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzIyMDUsImV4cCI6MjA2NTUwODIwNX0.Qirr5lztuPvLXDENIJ1mQf5AoO5EQ5tKPbKM3tsmfkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);